### ISSUE TITLE
Error installation R version 3.6.0

### ISSUE THREAD

**Issue by marcomeola** [taolonglab/himap#2]
Describe the bug*
Staged install implemented in R v.3.6.0 is causing the package to not install.

ERROR: hard-coded installation path: please report to the package maintainer and use ‘--no-staged-install’

**Comment by marcomeola** [comment]
Workaround:
in RStudio with R v.3.6.0 set:
Sys.setenv(R_INSTALL_STAGED=FALSE)

then install himap with following code:
devtools::install_github('taolonglab/himap')

**Comment by igor25** [comment]
Hi Marco! Thank you so much for catching this! I've solved the issue by updating the DESCRIPTION package file (https://github.com/taolonglab/himap/commit/eb66651525a5b66b388804301988ca804b423239), so the install should work fine now (I just verified it on my clean Ubuntu VM).
