### ISSUE TITLE
Finished database available for download

### ISSUE THREAD

**Issue by aeschriefer** [taolonglab/himap#4]
I am interested in evaluating your himap pipeline after reading your preprint.  However, due to poor internet it will be difficult for me to download all of the full genome sequences as described in your himapdb build process.  I was wondering if the final 16S database used for evaluating the HMP mock sample was available for download anywhere?

**Comment by igor25** [comment]
Hi! You don't need to manually build the database if you're using 16S data done with either V4 or V3-V4 primers. Those are included in this R package and does not require any additional setup. If you just want the database files they're here:

https://github.com/taolonglab/himap/tree/master/inst/database

There are FASTA files, e.g. for V3-V4 its V3-V4_337F-805R_hang21_wrefseq_sequences_unique_variants.fasta, tables with copy numbers of each variant and pre-compiled BLAST database (.nin, .nhr and .nsq files).

**Comment by aeschriefer** [comment]
Thank you for your help! I'm glad I don't have to download all those genomes :)
