### ISSUE TITLE
New to R, help!

### ISSUE THREAD

**Issue by jacknicoludis** [taolonglab/himap#5]
I'm very interested in using HiMAP, but I'm not familiar with R at all. I've been trying to follow the installation instructions, but I've been having trouble getting the dependent packages to work. I wanted to know more about how you've installed R to help me troubleshoot things. I'm working on a Mac. I've been trying to use conda to set up an R environment and download the dependencies but there seems to be an issue with devtools when I do this, so devtools isn't able to get packages from github. Also, biocLite is not working with the newest version of R, so I'm not sure even which version of R to use. Did you use conda, brew, or a direct download for R? Any suggestions for setting up an R enivornment on a Mac?

**Comment by igor25** [comment]
Hi!

I'm also using a Mac. If I remember correctly, I first installed R directly from their website (which seem unnecessarily confusing for beginners). This is the exact version (3.5.2) that I am using right now:

https://cran.cnr.berkeley.edu/bin/macosx/el-capitan/base/R-3.5.2.pkg

This very rudimentary "base" version of R can run everything (and is essentially a window with a terminal), although it may be less user-friendly than RStudio, which is a fancy interface to use R. Rstudio can be installed from here:

https://download1.rstudio.org/desktop/macos/RStudio-1.2.1335.dmg

After this is done, follow the instructions starting from the Xcode command line tools, if you didn't already install that.

**Comment by jacknicoludis** [comment]
Thanks for the suggestion! I've downloaded R from this site and the dependencies worked. And I was able to follow through with the tutorial. 

Going back to the conda installation, I was able to get it working, but when I try to install HiMAP I get a warning that the Shortread package is unavailable. I install Shortread via bioconductor in conda using:

`conda install -c bioconda bioconductor-shortread`

But it still isn't located correctly. I'm guessing there's a way to indicate where/which ShortRead I'm using (or maybe some way to load ShortRead into R, but I'm not familiar enough to figure out where that could be. Do you have any ideas?

**Comment by jacknicoludis** [comment]
This actually doesn't seem to be an issue. I'm able to follow tutorial and get the same results.
